import type { Metadata } from "next";
import { Rock_Salt,Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const open_sans = Open_Sans({ subsets: ["latin"] ,});
export const rock_salt=Rock_Salt({weight:'400',subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={open_sans.className}>
      <body className="bg-gray-500" >
      <Navbar/>
        {children}
        </body>
    </html>
  );
}
