import type { Metadata } from "next";
import { open_sans } from "./font";

import "./globals.css";
import Navbar from "@/components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={open_sans.className}>
      <body className="bg-gray-500" >
      <Navbar/>
        {children}
        </body>
    </html>
  );
}
